version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      day: "saturday"
      timezone: "Europe/Berlin"

    groups:
      all-patches-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    labels:
      - "dependency"

    ignore:
      - dependency-name: "@angular/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@nestjs/jwt"
        version: [ ">11.0.0" ]
      - dependency-name: "@angular-devkit/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular-eslint/*"
        version: [ "version-update:semver-major" ]
      - dependency-name: "zone.js"
        version: [ "version-update:semver-major", "version-update:semver-minor" ]
