version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      day: "saturday"
      timezone: "Europe/Berlin"

    groups:
      all-patches-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
        commit-message:
          prefix: "[minor/patch]"

    labels:
      - "dependency"
      - "major"
